config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'

  get 'start', to: 'welcome#start'

  resources :cards, only: [:show] do
    member do
      get 'answer'
      get 'action'
    end

    collection do
      get 'results'
    end
  end

  devise_for :users,
             controllers: {
               sessions: 'users/sessions',
               registrations: 'users/registrations'
             }

  # 管理画面

  # https://www.tmp1024.com/programming/post-4661
  devise_for :admin_users,
             path: 'admin',
             only: [:sign_in, :sign_out, :session],
             controllers: {
               sessions: 'admin_users/sessions'
             }

  namespace 'admin' do
    root to: 'welcome#index'
    resources :cards
    resources :users
    resources :clients
    resources :admin_users, only: [:index]
  end

  # https://github.com/fgrehm/letter_opener_web
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/views/admin/_footer.html.erb
<!-- To the right -->
<div class="pull-right hidden-xs">
  そして 1,000 問！
</div>
<!-- Default to the left -->
<strong>Copyright &copy; 2018-2022 <%= link_to t(:app_name), root_path %>.</strong> All rights reserved.

app/views/admin/_header.html.erb
<%= link_to admin_root_path, { class: "logo" } do %>
  <span class="logo-mini"></span>
  <span class="logo-lg"><%= t :app_name %></span>
<% end %>

<!-- Header Navbar -->
<nav class="navbar navbar-static-top" role="navigation">
  <!-- Sidebar toggle button-->
  <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
    <span class="sr-only">Toggle navigation</span>
  </a>
  <!-- Navbar Right Menu -->
  <div class="navbar-custom-menu">
    <ul class="nav navbar-nav">

      <!-- Tasks Menu -->
      <li class="dropdown tasks-menu">
        <!-- Menu Toggle Button -->
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <i class="fa fa-flag-o"></i>
          <span class="label label-danger"><%= current_admin_user.card_owners.count %></span>
        </a>
        <ul class="dropdown-menu">
          <li class="header">問題作成数: <%= current_admin_user.card_owners.count %></li>
          <% year = Time.zone.now.year %>
          <% (1..12).each do |month| %>
            <li class="header">- <%= year %>/<%= month %>: <%= current_admin_user.count_card_owners_created_in_year_month(year, month) %></li>
          <% end %>
          <!--
          <li>
            <!-- Inner menu: contains the tasks ->
            <ul class="menu">
              <li>
                <!-- Task item ->
                <a href="#">
                  <!-- Task title and progress text ->
                  <h3>
                    100 問中
                    <small class="pull-right"><%= current_admin_user.card_owners.count %>%</small>
                  </h3>
                  <!-- The progress bar ->
                  <div class="progress xs">
                    <!-- Change the css width attribute to simulate progress ->
                    <div class="progress-bar progress-bar-aqua" style="width: <%= current_admin_user.card_owners.count %>%" role="progressbar" aria-valuenow="<%= current_admin_user.card_owners.count %>" aria-valuemin="0" aria-valuemax="100">
                      <span class="sr-only">20% Complete</span>
                    </div>
                  </div>
                </a>
              </li>
              <!-- end task item ->
            </ul>
          </li>
          -->
          <li class="footer">
            <a href="#">作成した問題</a>
          </li>
        </ul>
      </li>

      <!-- User Account Menu -->
      <li class="dropdown user user-menu">
        <!-- Menu Toggle Button -->
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <!-- The user image in the navbar-->
          <!--<img src="https://almsaeedstudio.com/themes/AdminLTE/dist/img/user2-160x160.jpg" class="user-image" alt="User Image">-->
          <!-- hidden-xs hides the username on small devices so only the image appears. -->
          <span class="hidden-xs"><%= current_admin_user.email %></span>
        </a>
        <ul class="dropdown-menu">
        </ul>
      </li>

      <li>
        <%= link_to destroy_admin_user_session_path, method: :delete do %>
          ログアウト
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/admin/_sidebar.html.erb
<!-- Sidebar Menu -->
<ul class="sidebar-menu" data-widget="tree">
  <li class="header">メイン</li>
  <!-- Optionally, you can add icons to the links -->
  <% if request.path_info == admin_cards_path %>
    <li class="active">
  <% else %>
    <li>
  <% end %>
    <%= link_to admin_cards_path do %>
      <i class="fa fa-link"></i> <span>カード一覧</span>
    <% end %>
  </li>
  <% if request.path_info == admin_clients_path %>
    <li class="active">
  <% else %>
    <li>
  <% end %>
    <%= link_to admin_clients_path do %>
      <i class="fa fa-link"></i> <span>クライアント一覧</span>
    <% end %>
  </li>
  <% if request.path_info == admin_users_path %>
    <li class="active">
  <% else %>
    <li>
  <% end %>
    <%= link_to admin_users_path do %>
      <i class="fa fa-link"></i> <span>ユーザー一覧</span>
    <% end %>
  </li>
  <li class="treeview">
    <a href="#"><i class="fa fa-link"></i> <span>設定</span>
      <span class="pull-right-container">
        <i class="fa fa-angle-left pull-right"></i>
      </span>
    </a>
    <ul class="treeview-menu">
      <li>
        <%= link_to admin_admin_users_path do %>
          管理ユーザー
        <% end %>
      </li>
    </ul>
  </li>
</ul>
<!-- /.sidebar-menu -->