config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'

  get 'start', to: 'welcome#start'

  resources :cards, only: [:show] do
    member do
      get 'answer'
      get 'action'
    end

    collection do
      get 'results'
    end
  end

  devise_for :users,
             controllers: {
               sessions: 'users/sessions',
               registrations: 'users/registrations'
             }

  # 管理画面

  # https://www.tmp1024.com/programming/post-4661
  devise_for :admin_users,
             path: 'admin',
             only: [:sign_in, :sign_out, :session],
             controllers: {
               sessions: 'admin_users/sessions'
             }

  namespace 'admin' do
    root to: 'welcome#index'
    resources :cards
    resources :users
    resources :clients
    resources :admin_users, only: [:index]
  end

  # https://github.com/fgrehm/letter_opener_web
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/card.rb
class Card < ApplicationRecord
  has_many :log_actions, dependent: :destroy
  has_many :client_card_results, dependent: :destroy
  has_one :card_owner, dependent: :destroy

  def self.ransackable_attributes(auth_object = nil)
    ["answer", "comment", "question"]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end

  # 特定のクライアントの正答率が低い順
  scope :order_by_rate_ok_client, -> (client) {
    # これだと内部結合 (一度も答えていない問題が出力されない)
    #joins(:client_card_results).where(client_card_results: {client_id: client.id}).order("client_card_results.rate_ok")

    # ここら辺はドキュメント化しておかないと後から見たときにわからなそう

    # 外部結合する前に client_card_results.client_id = #{client.id} として、
    # 特定のクライアントのみの client_card_results と結合している
    # 一度も回答していないものが最後に固まる → TODO: これを 0% 扱いにできるか？
    joins("LEFT OUTER JOIN client_card_results ON (cards.id = client_card_results.card_id AND client_card_results.client_id = #{client.id})").order("client_card_results.rate_ok")
  }

  # 正答率をカードにキャッシュ
  def update_rate_ok
    self.rate_ok = self.correct_answer_rate
    self.save
  end

  def count_action_ok
    # 1 はなんとかせな
    self.log_actions.where(action: LogAction::ACTION_OK).count
  end

  def count_action_ng
    self.log_actions.where(action: LogAction::ACTION_NG).count
  end

  # 正答率
  def correct_answer_rate
    count_action_ok = self.count_action_ok
    count_action_ng = self.count_action_ng

    return 0 if (count_action_ok + count_action_ng) == 0

    # どっちがか float なら結果も float
    return count_action_ok / (count_action_ok + count_action_ng).to_f
  end

  # TODO: あとで効率化
  def correct_answer_rate_by_client(client)
    result = ClientCardResult.find_by(client: client, card: self)
    if result.nil?
      return nil
    else
      return result.rate_ok
    end
  end

  # 検索の時に使うキーワード
  def keyword_for_search
    return question.gsub(/\(.*\)/, "").gsub(/（.*）/, "").strip
  end

  #
  # 次のカード取得
  #
  # - LogAction が少ない場合に注意
  # - カードが少ない場合に注意
  #
  def self.get_next_card(client)
    # 3 つ前が間違いだったらそれを出題
    log_actions = LogAction.where(client: client).order(created_at: :desc).limit(3 + 1)  # 最新の 4 つの結果 (今回のも含む)
    log_action_this_time = log_actions.first  # 今回の結果
    log_action_prev_3    = log_actions.last   # 3 つ前の結果
    if (log_actions.size == 4)  # まだ 4 回答えてない場合は無視
      if (log_action_prev_3.action == LogAction::ACTION_NG)
        return log_action_prev_3.card
      end
    end

    # カード 1 枚だけの場合は毎回、今回と同じになってしまうため、特別処理
    return Card.last if Card.count == 1

    # ランダムに次のカードを決める (カード 1 枚だけだと無限ループ)
    loop do
      next_card = Card.offset(rand(Card.count)).first
      return next_card if next_card.id != log_action_this_time.card.id  # 違うのがでたら止める
    end
  end
end

app/controllers/admin/cards_controller.rb
class Admin::CardsController < Admin::ApplicationController
  def index
    @ransack = Card.ransack(params[:q])
    @ransack.sorts = "id DESC" if @ransack.sorts.empty?  # デフォルトのソート順
    @cards = @ransack.result.page(params[:page])
  end

  def show
    @card = Card.find(params[:id])
    @log_actions = @card.log_actions.order(id: :desc).includes(:client).page(params[:page])
  end

  def new
    @card = Card.new
  end

  def edit
    @card = Card.find(params[:id])
  end

  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        CardOwner.create(card: @card, admin_user: current_admin_user)  # TODO: トランザクションできちんと

        SlackNotifier.notify("漢検問題追加 - #{@card.id}: #{@card.question}")

        format.html { redirect_to admin_cards_url, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @card = Card.find(params[:id])

    respond_to do |format|
      if @card.update(card_params)
        SlackNotifier.notify("漢検問題更新 - #{@card.id}: #{@card.question}")

        format.html { redirect_to admin_cards_url, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @card = Card.find(params[:id])

    @card.destroy
    SlackNotifier.notify("漢検問題削除 - #{@card.id}: #{@card.question}")
    respond_to do |format|
      format.html { redirect_to admin_cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def card_params
      params.require(:card).permit(:question, :answer, :comment)
    end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def show
    @card = Card.find(params[:id])

    @latest_log_actions = LogAction.where(client: @client, card: @card).where(action: [LogAction::ACTION_OK, LogAction::ACTION_NG]).order(id: :desc).limit(10)
  end

  def answer
    @card = Card.find(params[:id])

    # 解答表示ログ記録
    if not @client.is_bot?
      LogAction.create(client: @client, card: @card)
    end
  end

  def action
    if @client.is_bot?
      redirect_to root_path
      return
    end

    card = Card.find(params[:id])

    # TODO: 本当はトランザクション

    # アクションログ記録
    if not params[:act].nil? and not @client.is_bot?
      log_action = LogAction.where(client: @client).order(id: :desc).first
      if log_action.card.id == card.id
        log_action.action = params[:act]
        log_action.save  # TODO: エラー処理
      end
    end

    # カードにアクションを起こすたびに正答率更新
    card.update_rate_ok

    # クライアントのカード毎の結果を記録
    ClientCardResult.update(@client, card)

    # 次のカードを決める
    next_card = Card.get_next_card(@client)

    redirect_to next_card
  end

  # 正答率一覧
  def results
    # ボットには表示させない
    render plain: "ok" and return if browser.bot?

    @cards = Card.order_by_rate_ok_client(@client).page(params[:page]).per(10)
  end
end

app/controllers/kanken8/cards_controller.rb
class Kanken8::CardsController < CardsController
  def show
    super
  end

  def answer
    super
  end

  def action
    super
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_card.html.slim
tr
  td = card.question
  td
   .text-right.text-muted
      - if card.correct_answer_rate_by_client(@client).nil?
        | -
      - else
        = number_with_precision(card.correct_answer_rate_by_client(@client) * 100, precision: 1)
        | %
  td
    .text-right.text-muted
      = number_with_precision(card.correct_answer_rate * 100, precision: 1)
      | %
  td.text-center = link_to "答え", answer_card_path(card), class: "btn btn-danger"

app/views/cards/answer.html.slim
- set_meta_tags title: "答え 「#{@card.question}」"

.row.mt-3
  .col-12
    h2.h4.my-3 答え

    .card
      .card-body
        .text-right.text-muted
          | 正答率:&nbsp;
          = number_with_precision(@card.correct_answer_rate * 100, precision: 1)
          | %
        h3.card-title.text-danger
          = @card.answer
        .card-subtitle.mb-2.text-muted
          = @card.question
      .card-footer
        p
          = @card.comment.html_safe
        = link_to "Google 検索", "https://www.google.com/search?q=#{@card.keyword_for_search}", { class: "btn btn-secondary btn-sm", target: "_blank" }
        | &nbsp;
        = link_to "青空文庫検索", "https://myokoym.net/aozorasearch/search?word=#{@card.keyword_for_search}", { class: "btn btn-secondary btn-sm", target: "_blank" }

/.row
  .col-12
    p スポンサーリンク
    .border
      == render "shared/adsense"

.row
  .col-12
    = link_to "次の問題", action_card_path(@card), class: "btn btn-primary btn-block", rel: "nofollow"

.row
  .col-6
    = link_to "間違えた…", action_card_path(@card, { act: LogAction::ACTION_NG }), class: "btn btn-warning btn-block", rel: "nofollow"
  .col-6
    = link_to "正解した！", action_card_path(@card, { act: LogAction::ACTION_OK }), class: "btn btn-success btn-block", rel: "nofollow"

app/views/cards/results.html.slim
- set_meta_tags og: { title: default_meta_tags[:site] }

.row.mt-4
  .col-12
    = paginate @cards, window: 1

    table.table.table-bordered.table-hover
      thead
        tr
          th rowspan=2 問題
          th colspan=2 正答率
          th rowspan=2
        tr
          th あなた
          th みんな
      tbody
        = render partial: "card", collection: @cards

    = paginate @cards, window: 1

app/views/cards/show.html.slim
- set_meta_tags title: "問題 「#{@card.question}」"

.row.mt-3
  .col-12
    h2.h4.my-3 問題

    .card
      .card-body
        .text-right.text-muted
          | 正答率:&nbsp;
          = number_with_precision(@card.correct_answer_rate * 100, precision: 1)
          | %
        h3.card-title
          = @card.question

.row
  .col-12
    .card
      .card-header
        | あなたの結果 （新 ←→ 古）

      .card-body
        - if @latest_log_actions.size == 0
          .text-muted （まだ結果がありません）
        - else
          - @latest_log_actions.each do |log_action|
            - if log_action.action == LogAction::ACTION_OK
              | ○
            - elsif log_action.action == LogAction::ACTION_NG
              | ×

/.row
  .col-12
    p スポンサーリンク
    .border
      == render "shared/affiliate"

.row
  .col-12
    = link_to "答え", answer_card_path(@card), class: "btn btn-danger btn-block"